#! /bin/sh
bspc rule -r "*"

# killall bspswallow
# pidof bspswallow | bspswallow &
#
# "一", "二", "三", "四", "五",
bspc monitor -d 一 二 三 四 五 六 七 八 九

bspc monitor DisplayPort-0 -d 1 2 3 4 5 6 7
bspc monitor DisplayPort-1 -d 8 9
bspc monitor HDMI-A-0 -d 10

bspc config border_width 2
bspc config window_gap 2

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true

###---Global Settings---###

bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_modifier lock
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus none

bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config normal_border_color "#4c566a"
bspc config active_border_color "#1e1e1e"
bspc config focused_border_color "#327bd1"
bspc config presel_feedback_color "#327bd1"
bspc config urgent_border_color "#dd2727"

###---Monitor And Desktop Settings----###
# bspc config top_padding 32
# bspc config bottom_padding 0
# bspc config left_padding 0
# bspc config right_padding 0
# bspc config border_width 2
# bspc config window_gap 10

###---Rules---###
bspc rule -a mpv state=fullscreen
bspc rule -a Zathura state=tiled
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

conky -q -c ~/.config/conky/conky1/conkyrc1 &
picom &
sxhkd &
dunst &
redshift -O 5000 & 
random-wallpaper.sh & # Not working
xset r rate 300 50 &
xmodmap ~/.Xmodmap &

polybar -r main --config=$HOME/.config/polybar/config.ini &
