#!/usr/bin/env bash

# Info: this is a script to launch other rofi scripts,

declare -A LABELS
declare -A COMMANDS

########################################################
#  ____        __ _       ____                         #
# |  _ \ ___  / _(_)     | __ )  __ _ _ __   __ _ ___  #
# | |_) / _ \| |_| |_____|  _ \ / _` | '_ \ / _` / __| #
# |  _ < (_) |  _| |_____| |_) | (_| | | | | (_| \__ \ #
# |_| \_\___/|_| |_|     |____/ \__,_|_| |_|\__, |___/ #
#                                           |___/      #
########################################################

# edit/add new bookmarks
# COMMANDS["editbookmarks"]="$EDITORGUI $HOME/.config/surfraw/bookmarks"
# LABELS["editbookmarks"]=""
# All applications
COMMANDS["exec"]="rofi -show run -show -modi run"
LABELS["exec"]=""

COMMANDS["apps"]="$HOME/.config/rofi/appmenu/launcher.sh"
LABELS["apps"]="Applications"


COMMANDS["password"]="$HOME/.config/rofi/launchers/rofi-keepassXC -d $HOME/Documents/passwords/Passwords.kdbx" 
LABELS["password"]=""


COMMANDS["keys"]="rofi -show keys"
LABELS["keys"]=""

# firefox bookmarks
COMMANDS["firefox-bookmarks"]="$HOME/.config/rofi/launchers/rofi-firefox-bookmarks"
LABELS["firefox-bookmarks"]=""

COMMANDS["aliases"]="$HOME/.config/rofi/launchers/rofi-aliases"
LABELS["aliases"]=""

# Music running through rofi
COMMANDS["music"]="$HOME/.config/rofi/launchers/rofi-audio"
LABELS["music"]=""

# Watch Youtube Videos
COMMANDS["Youtube"]='/usr/bin/ytfzf -D'
LABELS["Youtube"]=""

COMMANDS["Books"]="$HOME/.config/rofi/launchers/rofi-books"
LABELS["Books"]=""

# GLobal Search in folder
COMMANDS["Global"]='rofi -modi "Global Search":"$HOME/.config/rofi/launchers/rofi-spotlight" -show "Global Search"'
LABELS["Global"]=""

# search local files
COMMANDS["locate"]="$HOME/.config/rofi/launchers/rofi-locate"
LABELS["locate"]=""

# Watch your best twitch Streamers
COMMANDS["twitch"]="$HOME/.config/rofi/launchers/rofi-twitch"
LABELS["twitch"]=""

# text snippets
COMMANDS["snippet"]="$HOME/.config/rofi/launchers/rofi-snippet"
LABELS["snippet"]=""

# text snippet for multisnippet (aka a block of text)
COMMANDS["multisnippet"]="$HOME/.config/rofi/launchers/rofi-multisnippet"
LABELS["multisnippet"]=""

# open custom web searches
COMMANDS["websearch"]="$HOME/.config/rofi/launchers/rofi-surfraw-websearch"
LABELS["websearch"]=""

# Change theme of rofi
COMMANDS["theme"]='rofi-theme-selector'
LABELS["theme"]=""

# show clipboard history
# source: https://bitbucket.org/pandozer/rofi-clipboard-manager/overview
# COMMANDS["clipboard"]='rofi -modi "clipboard:$HOME/.bin/rofi-clipboard-manager/mclip.py menu" -show clipboard && $HOME/.bin/rofi-clipboard-manager/mclip.py paste'
# LABELS["clipboard"]=""

################################################################################
# do not edit below
################################################################################

##
# Generate menu
##

function print_menu() {
    for key in "${!LABELS[@]}"; do
        echo "$key    ${LABELS[0]}"
        #   echo "$key    ${LABELS[$key]}"
        # my top version just shows the first field in labels row, not two words side by side
    done
}

##
# Show rofi.
##
function start() {
    # print_menu | rofi -dmenu -p "?=>"
    print_menu | sort | rofi -dmenu -mesg ">>> launch your collection of rofi scripts" -i -p "rofi-bangs: "

}

# Run it
value="$(start)"

# Split input.
# grab upto first space.
choice=${value%%\ *}
# graph remainder, minus space.
input=${value:$((${#choice} + 1))}

##
# Cancelled? bail out
##
if test -z "${choice}"; then
    exit
fi

# check if choice exists
if test ${COMMANDS[$choice]+isset}; then
    # Execute the choice
    eval echo "Executing: ${COMMANDS[$choice]}"
    eval ${COMMANDS[$choice]}
else
    eval "$choice" | rofi
    # prefer my above so I can use this same script to also launch apps like geany or leafpad etc (DK)
    #   echo "Unknown command: ${choice}" | rofi -dmenu -p "error"
fi
