#!/bin/bash

echo "$ALIASDIR" | grep -e 'alias.*=' -e '=.*alias' | cut -d " " -f2- \
    | awk 'BEGIN {FS="="} {for(i=2;i<=NF;i++){gsub("\"","",$2);gsub("\047","",$2);printf ("%-40s %s \n",$1,$2) ;}}' \
    | rofi -dmenu | cut -d " " -f2- | xargs -I {} alacritty -e "{}"
