-- dap.adapters.python = {
-- type = 'executable',
-- command = '/home/precision/Softwares/anaconda3/envs/fastai/bin/python',
-- args = {'-m', 'debugpy.adapter'}
-- }
---- dap.defaults.fallback.external_terminal = {command = '/usr/bin/alacritty', args = {'-e'}}
----
-- dap.configurations.python = {
-- {
---- The first three options are required by nvim-dap
-- type = 'python', -- the type here established the link to the adapter definition: `dap.adapters.python`
-- request = 'launch',
-- name = "Launch file",

-- program = "${file}", -- This configuration will launch the current file if used.
-- pythonPath = function()
---- debugpy supports launching an application with a different interpreter then the one used to launch debugpy itself.
---- The code below looks for a `venv` or `.venv` folder in the current directly and uses the python within.
---- You could adapt this - to for example use the `VIRTUAL_ENV` environment variable.
-- if vim.fn.executable('/home/precision/Softwares/anaconda3/envs/fastai/bin/python') == 1 then
-- return '/home/precision/Softwares/anaconda3/envs/fastai/bin/python'
-- else
-- return '/usr/bin/python'
-- end
-- end
-- }
-- }
